#Timing trials for MCMC posterior samples via Adaptive Metropolis-Hastings

path <- "C:\\Users\\scanz\\Desktop\\Magistrale\\Extreme Value Theory\\Code\\"
source(paste0(path ,"functions.R"))

#Total chain: computation of a single chain of length N;
#Unified chains: computation of k chains of length N/k --> these chains are 
#constructed in a loop in order to start the next in the last point of the previous
#chain.

#Simulation setting
#Sample size
n <- 1000
#Exceeding probability used in the estimation
t.prob <- 0.05
#Number of exceedances used in the estimation
k <- n * t.prob
#Block-size for the correspoding block maxima approach
m <- 1/t.prob
#Exceeding probability used for prediction
p <- 1/n
#Return period
T.ret <- 50

#Unit Fréchet example
#Fréchet parameters
shape <- 1 #Inverse of the tail index
loc <- 0   #Location
scale <- 1 #Scale
#Set norming constants
#Centering
bn <- (log(n/k) - log(n/k-1))^(-1/shape)
#Scaling
an <- 1/(shape*(n/k-1)) * (log(n/k)-log(n/k-1))^(-1/shape-1)

#Define the true parameters
true.par <- c(1/shape, bn, an)
#Define true extreme quantile
Q.ext.true <- qfrechet(1 - p, loc, scale, shape)
#Define true return level
R.lev.true <- qgev(1 - 1/T.ret, bn, an, 1/shape)

#Define the estimation setting
start <- c(0.1, 0.1, 1)
set.seed(1)
data <- rfrechet(n, loc, scale, shape)
th <- quantile(data, probs=1-t.prob, type=3)

#Timing trials
library(tictoc)
#Overall posterior sample desired
R.tot <- 10000
#Number of posterior subsamples of length R.tot/R.trials
R.trials <- 10
#Total timing
t.tot <- 0
#split timing
t.trials <- rep(0, R.trials)
#Prameters graphical labels
lab <- c(expression(gamma), expression(mu), expression(delta))

#Timing comparison
#Total chain
tic()
set.seed(0)
fit.bayes.tot <- fit.gev.inference(data = data, t = th, t.prob = t.prob,
                                   llik.type = "Gev-Cens", T.ret = T.ret, p = p,
                                   par0 = start, hessian = TRUE, inf.type = "Bayes",
                                   R = R.tot)
cat("\n", R.tot, " samples: ")
time <- toc()
t.tot <- time$toc - time$tic

#Unified chains
tot.par <- NULL
tot.q.ext <- c()
tot.r.lev <- c()
#Starting point
start <- start
for(i in 1:R.trials){
  tic()
  set.seed(i)
  fit.bayes <- fit.gev.inference(data = data, t = th, t.prob = t.prob,
                                 llik.type = "Gev-Cens", T.ret = T.ret, p = p,
                                 par0 = start, hessian = TRUE, inf.type = "Bayes",
                                 R = R.tot/R.trials)
  #Unification
  tot.par <- rbind(tot.par, fit.bayes$parameters)
  tot.q.ext <- c(tot.q.ext, fit.bayes$Q.extreme)
  tot.r.lev <- c(tot.r.lev, fit.bayes$R.level)
  #Starting from the last value generated by the previous iteration...
  start <- as.vector(tot.par[dim(tot.par)[1],])
  cat("\n", i*(R.tot/R.trials), " samples: ")
  time <- toc()
  t.trials[i] <- time$toc - time$tic
}

#Comparisons
par(mfrow = c(2,3))

#Parameters (gamma, mu, delta)
cat("\n Parameters: total chain")
summary(fit.bayes.tot$parameters)
cat("\n Parameters: unified chains")
summary(tot.par)
for(i in 1:3){
  #Total chain
  #Trace plot
  plot(1:length(fit.bayes.tot$parameters[,i]), fit.bayes.tot$parameters[,i], type = "l",
       xlab = lab[i], ylab = "MCMC chain", main = "Trace plot (total chain)")
  abline(h = true.par[i], col = "green", lty = "dashed", lwd = 3)
  #ACF plot
  acf(fit.bayes.tot$parameters[,i], lag.max = 100,
      xlab = lab[i], ylab = "ACF", main = "Autocorrelation plot (lag.max = 100, total chain)")
  #Histogram
  hist(fit.bayes.tot$parameters[,i], nclass = 50, probability = TRUE,
       xlab = lab[i], main = "Posterior distribution (total chain)")
  abline(v = true.par[i], col = "blue", lty = 2, lwd = 2)
  abline(v = emp.hpd(fit.bayes.tot$parameters[,i], conf = 0.95), col = "red",
         lty = 3, lwd = 2)
  
  #Unified chains
  #Trace plot
  plot(1:length(tot.par[,i]), tot.par[,i], type = "l",
       xlab = lab[i], ylab = "MCMC chain", main = "Trace plot (unified chains)")
  abline(h = true.par[i], col = "green", lty = "dashed", lwd = 3)
  #ACF plot
  acf(tot.par[,i], lag.max = 100,
      xlab = lab[i], ylab = "ACF", main = "Autocorrelation plot (lag.max = 100, unified chains)")
  #Histogram
  hist(tot.par[,i], nclass = 50, probability = TRUE,
       xlab = lab[i], main = "Posterior distribution (unified chains)")
  abline(v = true.par[i], col = "blue", lty = 2, lwd = 2)
  abline(v = emp.hpd(tot.par[,i], conf = 0.95), col = "red",
         lty = 3, lwd = 2)
}

#Extreme quantile
cat("\n Extreme quantile: total chain")
summary(fit.bayes.tot$Q.extreme)
cat("\n Extreme quantile: unified chains")
summary(tot.q.ext)
#Total chain
#Trace plot
plot(1:length(fit.bayes.tot$Q.extreme), fit.bayes.tot$Q.extreme, type = "l",
     xlab = "Extreme quantile", ylab = "MCMC chain", main = "Trace plot (total chain)")
abline(h = Q.ext.true, col = "green", lty = "dashed", lwd = 3)
#ACF plot
acf(fit.bayes.tot$Q.extreme, lag.max = 100, xlab = "Extreme quantile",
    ylab = "ACF", main = "Autocorrelation plot (lag.max = 100, total chain)")
#Histogram
hist(fit.bayes.tot$Q.extreme, nclass = 50, probability = TRUE,
     xlab = "Extreme quantile", main = "Posterior distribution (total chain)")
abline(v = Q.ext.true, col = "blue", lty = 2, lwd = 2)
abline(v = emp.hpd(fit.bayes.tot$Q.extreme, conf = 0.95), col = "red",
       lty = 3, lwd = 2)

#Unified chains
#Trace plot
plot(1:length(tot.q.ext), tot.q.ext, type = "l",
     xlab = "Extreme quantile", ylab = "MCMC chain", main = "Trace plot (unified chains)")
abline(h = Q.ext.true, col = "green", lty = "dashed", lwd = 3)
#ACF plot
acf(tot.q.ext, lag.max = 100, xlab = "Extreme quantile",
    ylab = "ACF", main = "Autocorrelation plot (lag.max = 100, unified chains)")
#Histogram
hist(tot.q.ext, nclass = 50, probability = TRUE,
     xlab = "Extreme quantile", main = "Posterior distribution (unified chains)")
abline(v = Q.ext.true, col = "blue", lty = 2, lwd = 2)
abline(v = emp.hpd(tot.q.ext, conf = 0.95), col = "red",
       lty = 3, lwd = 2)

#Return level
cat("\n Return level: total chain")
summary(fit.bayes.tot$R.level)
cat("\n Return level: unified chains")
summary(tot.r.lev)
#Total chain
#Trace plot
plot(1:length(fit.bayes.tot$R.level), fit.bayes.tot$R.level, type = "l",
     xlab = "Return level", ylab = "MCMC chain", main = "Trace plot (total chain)")
abline(h = R.lev.true, col = "green", lty = "dashed", lwd = 3)
#ACF plot
acf(fit.bayes.tot$R.level, lag.max = 100, xlab = "Return level",
    ylab = "ACF", main = "Autocorrelation plot (lag.max = 100, total chain)")
#Histogram
hist(fit.bayes.tot$R.level, nclass = 50, probability = TRUE,
     xlab = "Return level", main = "Posterior distribution (total chain)")
abline(v = R.lev.true, col = "blue", lty = 2, lwd = 2)
abline(v = emp.hpd(fit.bayes.tot$R.level, conf = 0.95), col = "red",
       lty = 3, lwd = 2)

#Unified chains
#Trace plot
plot(1:length(tot.r.lev), tot.r.lev, type = "l",
     xlab = "Return level", ylab = "MCMC chain", main = "Trace plot (unified chains)")
abline(h = R.lev.true, col = "green", lty = "dashed", lwd = 3)
#ACF plot
acf(tot.r.lev, lag.max = 100, xlab = "Return level",
    ylab = "ACF", main = "Autocorrelation plot (lag.max = 100, unified chains)")
#Histogram
hist(tot.r.lev, nclass = 50, probability = TRUE,
     xlab = "Return level", main = "Posterior distribution (unified chains)")
abline(v = R.lev.true, col = "blue", lty = 2, lwd = 2)
abline(v = emp.hpd(tot.r.lev, conf = 0.95), col = "red",
       lty = 3, lwd = 2)

par(mfrow = c(1,1))

#Timing results
cat("\n", t.tot, "\n", t.trials, "\n", sum(t.trials))